name: 資料收集工作流程
run-name: 資料收集

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 執行（台灣時間早上 8:00）
  workflow_dispatch:      # 允許手動觸發

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v2
      
    - name: 設定 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: 執行api爬蟲
      run: |
        echo "開始執行api爬蟲..."
        python api.py
        echo "api爬蟲完成"
    
    - name: 執行static爬蟲
      run: |
        echo "開始執行static爬蟲..."
        python static.py
        echo "static爬蟲完成"
        
    - name: 提交更新的資料
      run: |
        git config --global user.name "crawler-bot"
        git config --global user.email "crawler-bot@gmail.com"
        git add . && git commit -m "daily crawl"
        git push origin main    